# Generated by Django 5.2.7 on 2025-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos/'),
        ),
    ]
